  name: Report coverage to SonarCloud
  
  on: [pull_request]
  jobs:
    build-branch:
      runs-on: ubuntu-latest

      name: Test coverage report.
      steps:
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      
      - name: Set up maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.1

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
        
      - name: Install dependencies
        run : |
            pip install -r requirements-dev.txt
            pip install -r requirements-test.txt
            
      - name: Run tests
        env:
          HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
        run : python run_tests.py
      
      - name: Fix for coverage.xml
        run: coverage xml -i
            
      - name: Analyze with SonarCloud for Merge
        if: github.event_name == 'push'
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: '8116e073ff512b3ef3119506be6935530b34f46f' 
        with:
          args: >
            -Dsonar.organization=devopshazelcast-github
            -Dsonar.projectKey=hazelcast_hazelcast-python-client
            -Dsonar.python.coverage.reportPaths=./coverage.xml
            
      - name: Analyze with SonarCloud for PR
        if: github.event_name == 'pull_request'
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: '8116e073ff512b3ef3119506be6935530b34f46f'
        with:
          args: >
            -Dsonar.organization=devopshazelcast-github
            -Dsonar.projectKey=hazelcast_hazelcast-python-client
            -Dsonar.python.coverage.reportPaths=./coverage.xml
            -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
            -Dsonar.pullrequest.key=${{ github.event.number }} 
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}    
